name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Install project dependencies
        run: mise run install

      - name: Sync Astro types
        run: mise run check

      - name: Build site
        run: mise run build
